#############################################################################
# Makefile for building: libmaps.so
# Generated by qmake (2.01a) (Qt 4.8.0) on: ?? 13. ??? 17:26:27 2012
# Project:  maps.pro
# Template: app
# Command: C:\necessitas\android\qt\480\armeabi\bin\qmake.exe -spec ..\necessitas\Android\Qt\480\armeabi\mkspecs\android-g++ -win32 -o Makefile maps.pro
#############################################################################

####### Compiler, tools and options

CC            = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-gcc
CXX           = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT -DQT_NO_DYNAMIC_CAST -DQT_SHARED
CFLAGS        = -Wno-psabi -march=armv5te -mtune=xscale -msoft-float -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -g -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Wall -Wno-psabi -W $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv5te -mtune=xscale -msoft-float -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -DQT_NO_QWS_TRANSFORMED -O2 -g -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -Wall -Wno-psabi -W $(DEFINES)
INCPATH       = -I..\necessitas\Android\Qt\480\armeabi\mkspecs\android-g++ -I. -I..\necessitas\Android\Qt\480\armeabi\include\QtCore -I..\necessitas\Android\Qt\480\armeabi\include\QtGui -I..\necessitas\Android\Qt\480\armeabi\include\QtSql -I..\necessitas\Android\Qt\480\armeabi\include\QtSvg -I..\necessitas\Android\Qt\480\armeabi\include -IC:\necessitas\Android\Qt\480\armeabi\include/ActiveQt -I. -I. -I. -I..\necessitas\android-ndk-r6b\platforms\android-5\arch-arm\usr\include -I..\necessitas\android-ndk-r6b\sources\cxx-stl\gnu-libstdc++\include -I..\necessitas\android-ndk-r6b\sources\cxx-stl\gnu-libstdc++\libs\armeabi\include
LINK          = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:/necessitas/android-ndk-r6b/platforms/android-5/arch-arm/ -LC:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.4.3 -Wl,-rpath-link=C:/necessitas/android-ndk-r6b/platforms/android-5/arch-arm//usr/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared -Wl,-soname,libmaps.so -Wl,-rpath=C:/tmp/necessitas/unstable/Android/Qt/480/build-armeabi/install/lib
LIBS          = $(SUBLIBS)  -LC:/necessitas/android-ndk-r6b/sources/cxx-stl/gnu-libstdc++/libs/armeabi -LC:/necessitas/android-ndk-r6b/platforms/android-5/arch-arm//usr/lib -LC:\necessitas\Android\Qt\480\armeabi\lib -lQtSvg -L/tmp/necessitas/unstable/Android/Qt/480/build-armeabi/install/lib -L/tmp/necessitas/android-ndk-r6b/sources/cxx-stl/gnu-libstdc++/libs/armeabi -L/tmp/necessitas/android-ndk-r6b/platforms/android-5/arch-arm//usr/lib -lQtSql -lQtGui -lQtCore -lstdc++ -lsupc++ -llog -lz -lm -ldl -lc -lgcc 
AR            = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-ranlib
QMAKE         = C:\necessitas\android\qt\480\armeabi\bin\qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = copy /y
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
STRIP         = C:/necessitas/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-strip
INSTALL_FILE  = copy /y
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = copy /y
DEL_FILE      = del /q 2> NUL
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		map.cpp \
		svgview.cpp \
		..\necessitas\Android\Qt\480\armeabi\src\android\cpp\qtmain_android.cpp moc_map.cpp \
		moc_svgview.cpp \
		qrc_piu.cpp \
		qrc_karta.cpp
OBJECTS       = main.obj \
		map.obj \
		svgview.obj \
		qtmain_android.obj \
		moc_map.obj \
		moc_svgview.obj \
		qrc_piu.obj \
		qrc_karta.obj
DIST          = ..\necessitas\Android\Qt\480\armeabi\mkspecs\common\unix.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\linux.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base-unix.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\qws.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\qconfig.pri \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\modules\qt_webkit_version.pri \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_functions.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_config.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\exclusive_builds.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_pre.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_pre.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\release.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_post.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_post.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\stl.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\exceptions.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\warn_on.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\thread.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\moc.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\windows.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\rtti_off.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\resources.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\uic.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\yacc.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\lex.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\include_source_dir.prf \
		maps.pro
QMAKE_TARGET  = libmaps.so
DESTDIR       = 
TARGET        = libmaps.so

first: all
####### Implicit rules

.SUFFIXES: .obj .c .cpp .cc .cxx

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_map.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: maps.pro  ..\necessitas\Android\Qt\480\armeabi\mkspecs\android-g++\qmake.conf ..\necessitas\Android\Qt\480\armeabi\mkspecs\common\unix.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\linux.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base-unix.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\common\qws.conf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\qconfig.pri \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\modules\qt_webkit_version.pri \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_functions.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_config.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\exclusive_builds.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_pre.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_pre.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\release.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_post.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_post.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\stl.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\exceptions.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\warn_on.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\thread.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\moc.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\windows.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\rtti_off.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\resources.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\uic.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\yacc.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\lex.prf \
		..\necessitas\Android\Qt\480\armeabi\mkspecs\features\include_source_dir.prf \
		C:\necessitas\Android\Qt\480\armeabi\lib\libQtSvg.prl \
		C:\necessitas\Android\Qt\480\armeabi\lib\libQtGui.prl \
		C:\necessitas\Android\Qt\480\armeabi\lib\libQtCore.prl \
		C:\necessitas\Android\Qt\480\armeabi\lib\libQtSql.prl
	$(QMAKE) -spec ..\necessitas\Android\Qt\480\armeabi\mkspecs\android-g++ -win32 -o Makefile maps.pro
..\necessitas\Android\Qt\480\armeabi\mkspecs\common\unix.conf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\common\linux.conf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base.conf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\common\gcc-base-unix.conf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\common\qws.conf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\qconfig.pri:
..\necessitas\Android\Qt\480\armeabi\mkspecs\modules\qt_webkit_version.pri:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_functions.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt_config.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\exclusive_builds.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_pre.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_pre.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\release.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\default_post.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\default_post.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\stl.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\exceptions.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\warn_on.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\qt.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\thread.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\moc.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\windows.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\win32\rtti_off.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\resources.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\uic.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\yacc.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\lex.prf:
..\necessitas\Android\Qt\480\armeabi\mkspecs\features\include_source_dir.prf:
C:\necessitas\Android\Qt\480\armeabi\lib\libQtSvg.prl:
C:\necessitas\Android\Qt\480\armeabi\lib\libQtGui.prl:
C:\necessitas\Android\Qt\480\armeabi\lib\libQtCore.prl:
C:\necessitas\Android\Qt\480\armeabi\lib\libQtSql.prl:
qmake:  FORCE
	@$(QMAKE) -spec ..\necessitas\Android\Qt\480\armeabi\mkspecs\android-g++ -win32 -o Makefile maps.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp\libmaps.so1.0.0 $(MKDIR) .tmp\libmaps.so1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp\libmaps.so1.0.0\ && $(COPY_FILE) --parents map.h svgview.h .tmp\libmaps.so1.0.0\ && $(COPY_FILE) --parents piu.qrc karta.qrc .tmp\libmaps.so1.0.0\ && $(COPY_FILE) --parents main.cpp map.cpp svgview.cpp ..\necessitas\Android\Qt\480\armeabi\src\android\cpp\qtmain_android.cpp .tmp\libmaps.so1.0.0\ && $(COPY_FILE) --parents map.ui .tmp\libmaps.so1.0.0\ && (cd `dirname .tmp\libmaps.so1.0.0` && $(TAR) libmaps.so1.0.0.tar libmaps.so1.0.0 && $(COMPRESS) libmaps.so1.0.0.tar) && $(MOVE) `dirname .tmp\libmaps.so1.0.0`\libmaps.so1.0.0.tar.gz . && $(DEL_FILE) -r .tmp\libmaps.so1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_map.cpp moc_svgview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_map.cpp moc_svgview.cpp
moc_map.cpp: svgview.h \
		map.h
	C:\necessitas\Android\Qt\480\armeabi\bin\moc.exe $(DEFINES) $(INCPATH) map.h -o moc_map.cpp

moc_svgview.cpp: svgview.h
	C:\necessitas\Android\Qt\480\armeabi\bin\moc.exe $(DEFINES) $(INCPATH) svgview.h -o moc_svgview.cpp

compiler_rcc_make_all: qrc_piu.cpp qrc_karta.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_piu.cpp qrc_karta.cpp
qrc_piu.cpp: piu.qrc \
		1.GIF \
		splash1.PNG \
		screen.png
	C:\necessitas\Android\Qt\480\armeabi\bin\rcc.exe -name piu piu.qrc -o qrc_piu.cpp

qrc_karta.cpp: karta.qrc \
		map.svg
	C:\necessitas\Android\Qt\480\armeabi\bin\rcc.exe -name karta karta.qrc -o qrc_karta.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_map.h
compiler_uic_clean:
	-$(DEL_FILE) ui_map.h
ui_map.h: map.ui
	C:\necessitas\Android\Qt\480\armeabi\bin\uic.exe map.ui -o ui_map.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.obj: main.cpp map.h \
		svgview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

map.obj: map.cpp map.h \
		svgview.h \
		ui_map.h \
		scribblearea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.obj map.cpp

svgview.obj: svgview.cpp svgview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svgview.obj svgview.cpp

qtmain_android.obj: ..\necessitas\Android\Qt\480\armeabi\src\android\cpp\qtmain_android.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmain_android.obj ..\necessitas\Android\Qt\480\armeabi\src\android\cpp\qtmain_android.cpp

moc_map.obj: moc_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_map.obj moc_map.cpp

moc_svgview.obj: moc_svgview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_svgview.obj moc_svgview.cpp

qrc_piu.obj: qrc_piu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_piu.obj qrc_piu.cpp

qrc_karta.obj: qrc_karta.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_karta.obj qrc_karta.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)\libs\armeabi $(MKDIR) $(INSTALL_ROOT)\libs\armeabi 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)\libs\armeabi\$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)\libs\armeabi\$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)\libs\armeabi\$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)\libs\armeabi 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

